/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.devworkshop;

import com.thoughtworks.devworkshop.lending.Borrower;
import com.thoughtworks.devworkshop.lending.Lender;

public class App {
    public static void main(String[] args) {
        Lender lender1 = new Lender("lender1", 500.0);

        Borrower borrower1 = new Borrower("borrower1", 50.0);
        lender1.lend(100.0, borrower1);
        printStatus(lender1, borrower1);

        borrower1.payBack(100.0, lender1);

        printStatus(lender1, borrower1);
    }

    private static void printStatus(Lender lender1, Borrower borrower1) {
        System.out.println(lender1);
        System.out.println(borrower1);
    }
}
